---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/pomerium --version
      register: pomerium_test_output
    - name: pomerium --version
      debug:
        msg: '{{ pomerium_test_output.stdout }}'
