---
- name: Testing andrewrothstein.pomerium
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'pomerium --version'
      ansible.builtin.command: pomerium --version
      changed_when: false
      register: pomerium_test_output
    - name: Output from 'pomerium --version'
      ansible.builtin.debug:
        msg: '{{ pomerium_test_output.stdout }}'
