---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for pomerium:{{ pomerium_ver }} install
  ansible.builtin.stat:
    path: '{{ pomerium_install_dir }}'
  register: pomerium_binary
- name: Downloading and installing pomerium
  when: not pomerium_binary.stat.exists
  block:
    - name: Mkdir -p {{ pomerium_install_dir }}
      become: '{{ pomerium_elevate }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ pomerium_install_dir }}'
        state: directory
        mode: '755'
    - name: Download {{ pomerium_url }} to {{ pomerium_fqarchive }}
      become: '{{ pomerium_elevate }}'
      become_user: root
      ansible.builtin.get_url:
        url: '{{ pomerium_url }}'
        dest: '{{ pomerium_fqarchive }}'
        checksum: 'sha256:{{ pomerium_checksums_url }}'
        mode: '644'
    - name: Unarchive {{ pomerium_fqarchive }}
      become: '{{ pomerium_elevate }}'
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ pomerium_fqarchive }}'
        dest: '{{ pomerium_install_dir }}'
        creates: '{{ pomerium_install_dir }}/pomerium'
  always:
    - name: Rm -f {{ pomerium_fqarchive }}
      become: '{{ pomerium_elevate }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ pomerium_fqarchive }}'
        state: absent
- name: Link executables in {{ pomerium_parent_install_dir }}/bin
  become: '{{ pomerium_elevate }}'
  become_user: root
  with_items:
    - pomerium
  ansible.builtin.file:
    src: '{{ pomerium_install_dir }}/{{ item }}'
    dest: '{{ pomerium_parent_install_dir }}/bin/{{ item }}'
    state: link
